### ISSUE TITLE
Textarea - add TETextarea in Contact form example in Form Templates

### ISSUE THREAD

**Issue by iprzybysz** [mdbootstrap/Tailwind-Elements-React#63]
https://tailwind-elements.com/docs/standard/forms/form-templates/#contact

**Comment by ManavJoshi111** [comment]
Hey, I want to contribute to this, can you please describe this issue a bit more?

**Comment by iprzybysz** [comment]
Hey, it was a small change in documentation, which I've already done. Check out other tasks on our project board.
